# Generated by Django 3.1 on 2020-11-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0003_auto_20201117_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
